## This simple classifier was used to make the initial comparison between scikit-learn and Tribuo

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
#from sklearn import cross_validation
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# This is the classic Iris dataset
df = pd.read_csv('../../data/bezdekIris.data', header=None)
# print(df)

In [3]:
X = np.array(df[[0,1,2,3]])
y = np.array(df[4])

# class_le = LabelEncoder()
# y = class_le.fit_transform(df[4].values)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
print('Training data size = %d, number of features = %d' % (len(X_train), 4))
print('Testing data size = %d, number of features = %d' % (len(X_test), 4))

Training data size = 105, number of features = 4
Testing data size = 45, number of features = 4


In [4]:
stdscaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled = stdscaler.transform(X_train)
X_test_scaled  = stdscaler.transform(X_test)

In [5]:
# lr = LogisticRegression()
# lr.fit(X_train, y_train)
# lr.fit(X_train_scaled, y_train)

sgd = SGDClassifier(max_iter=1000, learning_rate='adaptive', epsilon=0.1, eta0=1.0)
sgd.fit(X_train, y_train)

SGDClassifier(eta0=1.0, learning_rate='adaptive')

In [6]:
# predicted = lr.predict(X_test)
# predicted = lr.predict(X_test_scaled)

predicted = sgd.predict(X_test)

In [7]:
print(classification_report(y_test, predicted))

                 precision    recall  f1-score   support

    Iris-setosa       0.93      1.00      0.97        14
Iris-versicolor       1.00      0.83      0.91        18
 Iris-virginica       0.87      1.00      0.93        13

       accuracy                           0.93        45
      macro avg       0.93      0.94      0.93        45
   weighted avg       0.94      0.93      0.93        45



In [8]:
print(confusion_matrix(y_test, predicted, labels=['Iris-versicolor', 'Iris-virginica', 'Iris-setosa']))

[[15  2  1]
 [ 0 13  0]
 [ 0  0 14]]
